platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven

inputs:
- name: Hello

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    cd Hello
    mvn package
    cp ./target/Hello-0.0.1-SNAPSHOT.jar ../built-project/demo.jar