resources:
- name: Hello
  type: git
  source:
    uri: https://github.com/brooklyyounce/concourse-spring-boot-maven.git
- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: younceb@goldmail.etsu.edu
    password: Brookly likes the number 47.
    organization: younceb-org
    space: development


jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: Hello, trigger: true}
  - task: build
    privileged: true
    file: build.yml
  - put: resource-deploy-web-app
    params:
      manifest: manifest.yml
      path: built-project/demo.jar

